### ISSUE TITLE
Stackable functions lose their bound Session State when they are stacked

### ISSUE THREAD

**Issue by mdgrs-mei** [StartAutomating/Posh#138]
Because the functions are stringified, they are made unbound. If users customize their prompt with modules, it might not work as expected.

Let's say you have a module that customizes the prompt:

```powershell
# MyModule.psm1
$moduleVar = 'Hello > '

$function:global:Prompt = {
    $moduleVar
}
```

Import MyModule and Posh, then call `Append`. 

```powershell
PS > Import-Module ./MyModule.psm1
Hello > Import-Module Posh
Hello > $Posh.Prompt.Append('>> ')
>> 
```

The last prompt shows `>> ` while `Hello > >> ` is expected.

**Comment by StartAutomating** [comment]
@mdgrs-mei did you define the global prompt _after_ Posh was loaded?

**Comment by mdgrs-mei** [comment]
@StartAutomating no, I defined the prompt before loading Posh. 

There is no problem if you define the prompt in the global session state. The issue only happens when you define it in a module like the example above.

**Comment by StartAutomating** [comment]
@mdgrs-mei what would be the desired experience?  Should all modifications to the prompt use the module scope of the first item, or do you want prompts to call each other directly, all the way down?

**Comment by mdgrs-mei** [comment]
I think each item in the prompt should be called directly in their session state.

If a user called Append with a ScriptBlock in a module, it would need to see variables in that module.

**Comment by StartAutomating** [comment]
@mdgrs-mei 

In order to do this right, we'd need each stackable function to not directly emebd the previous value, but instead _call_ the previous value.  Which, in turn, means we need to be able to determine the index of the current item, and refactor the existing ScriptMethods to use that index.

If you think you understand what I mean here, I'm happy to let you run with it.

Let me know and I will assign the issue to you.

**Comment by mdgrs-mei** [comment]
@StartAutomating I think I understand what you mean. I'll let you know again when I get a chance to look into this.

**Comment by mdgrs-mei** [comment]
@StartAutomating ok, can you assign the issue to me? I managed to make this work in my test code.
