### ISSUE TITLE
[int] | Format-Custom -View System.Type.Full gives an error

### ISSUE THREAD

**Issue by stefanstranger** [StartAutomating/Posh#211]
When running [int] | Format-Custom -View System.Type.Full

I get the following error:

Exception             : 
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling ".ctor" with "1" argument(s): "Cannot process argument because the value of argument "obj" is null. Change the value of argument "obj" to a non-null value."
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : PSArgumentNullException
        InvocationInfo        : 
            ScriptLineNumber : 4
            OffsetInLine     : 13
            HistoryId        : -1
            Line             :             $o =[PSObject]::new($MethodParameters[$n])

            PositionMessage  : At line:4 char:13
                               +             $o =[PSObject]::new($MethodParameters[$n])
                               +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 4
                                at <ScriptBlock>, <No file>: line 1
    TargetSite     : 
        Name          : CheckActionPreference
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation, Version=7.3.6.500, Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Exception calling ".ctor" with "1" argument(s): "Cannot process argument because the value of argument "obj" is null. Change the value of argument "obj" to a non-null value."
    InnerException : 
        Type        : System.Management.Automation.PSArgumentNullException
        ErrorRecord : 
            Exception             : 
                Type    : System.Management.Automation.ParentContainsErrorRecordException
                Message : Cannot process argument because the value of argument "obj" is null. Change the value of argument "obj" to a non-null value.
                HResult : -2146233087
            CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
            FullyQualifiedErrorId : ArgumentNull
        Message     : Cannot process argument because the value of argument "obj" is null. Change the value of argument "obj" to a non-null value.
        ParamName   : obj
        TargetSite  : Void .ctor(System.Object)
        Source      : System.Management.Automation
        HResult     : -2147467261
        StackTrace  : 
   at System.Management.Automation.PSObject..ctor(Object obj)
   at CallSite.Target(Closure, CallSite, Type, Object)
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     : 
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at <ScriptBlock>(Closure, FunctionContext)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at Microsoft.PowerShell.Commands.PSPropertyExpression.GetValue(PSObject target, Boolean eatExceptions)
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : PSArgumentNullException
InvocationInfo        : 
    ScriptLineNumber : 4
    OffsetInLine     : 13
    HistoryId        : -1
    Line             :             $o =[PSObject]::new($MethodParameters[$n])

    PositionMessage  : At line:4 char:13
                       +             $o =[PSObject]::new($MethodParameters[$n])
                       +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 4
                        at <ScriptBlock>, <No file>: line 1

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by StartAutomating** [comment]
@stefanstranger good catch!

I'll add some ifguards.
